spring.application.name=springAI
spring.ai.openai.api-key=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

